project_id = "gthtvpujwukbfgokghne"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.fluxo-0-detalhes-emissao]
verify_jwt = false

[functions.fluxo-0-listar-emissoes]
verify_jwt = false

[functions.fluxo-1-atualizar-emissao]
verify_jwt = false

[functions.fluxo-1-criar-emissao]
verify_jwt = false

[functions.fluxo-1-salvar-custos]
verify_jwt = false

[functions.fluxo-2-finalizar-proposta]
verify_jwt = false

[functions.fluxo-2-gerar-pdf]
verify_jwt = false

[functions.fluxo_custos_por_combinacao]
verify_jwt = false
